


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xiongwei
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    lettuce:
      pool:
        max-active: 10
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai


server:
  port: 8889
  servlet:
    context-path: /graduation


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.graduation.entity


file:
  #注意：结尾必须/
  uploadFolder: e:/upload/
  #注意：结尾必须**
  accessPath: /upload/**
  #注意：结尾必须/
  baseUrl: http://localhost:8889/job/upload/